---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Self-hosted Lambda runtime layer for Golang ARM executables."


Parameters:

  ContentS3Bucket:
    Type: String
    Description: >-
      S3 bucket where layer content resides.
    Default: "ary.pub-lambda-community"

  ContentS3Key:
    Type: String
    Description: >-
      Lambda layer content key path.
    Default: "go-arm-lambda/runtime-layer.zip"


Resources:

  RuntimeLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - provided.al2
      Content:
        S3Bucket: !Ref ContentS3Bucket
        S3Key: !Ref ContentS3Key
      Description: >-
        Lambda runtime layer that enables Golang ARM executables.
      LayerName: golang-arm-runtime
      LicenseInfo: MIT

  RuntimeLayerPermisson:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: "lambda:GetLayerVersion"
      LayerVersionArn: !Ref RuntimeLayer
      Principal: !Ref "AWS::AccountId"


Outputs:

  RuntimeLayerArn:
    Description: >-
      ARN of the Lambda layer containing the runtime boostrap.
    Value: !Ref RuntimeLayer
    Export:
      Name: !Sub "${AWS::StackName}:runtime-layer-arn"
